
name: CI

run-name: ${{ github.actor }} is learning GitHub Actions

# 触发条件
on:
  push:
    branches:
       - main

 # 任务
jobs:
    #任务名称
    app_deploy:
      # 服务器环境：最新版 Ubuntu
      runs-on: ubuntu-latest
      steps:
       # 拉取代码
       - name: Checkout
         uses: actions/checkout@v2
         with:
           persist-credentials: false
       # install
       - name: Install
         run: |
           npm install  # 安装依赖
           npm run dll 
       # 生成静态文件
       - name: Build
         run: |
           npm run build  # 执行打包命令
       # 部署到 GitHub Pages
       - name: Deploy
         uses: JamesIves/github-pages-deploy-action@v4.3.3
         with:
           ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
           BRANCH: gh-pages  
           FOLDER: dist # 生成的静态文件存放的地方
