
name: Docker Image CI

# 触发条件为 push
on:
  push:
    branches:
      - master
    # 修改文件范围, 不在范围内不触发
    paths:
      - 'public/**'
 # 任务
jobs:
    #任务名称
    app_deploy:
      # 服务器环境：最新版 Ubuntu
      runs-on: ubuntu-latest
      # 任务步骤
      steps:
       # 拉取代码
        - name: Checkout
          uses: actions/checkout@v2
          with:
            persist-credentials: false

        - name: Set up Docker Compose
          run: |
            sudo apt-get update
            sudo apt-get install -y docker-compose

        # #登录到 Docker Hub
        # - name: Login to Docker Hub
        #   uses: docker/login-action@v1
        #   with:
        #     username: ${{ secrets.DOCKERHUB_USERNAME }}
        #     password: ${{ secrets.DOCKERHUB_PASSWORD }}
       
       #  
        - name: Build and push Docker image
          run : |
            docker-compose up -d
